#! /usr/bin/python
# -*- coding: utf-8 -*-

import sqlite3, os, unittest
from debdeploy_joblog import *

class TestDeployJob(unittest.TestCase):

    if not os.path.exists("testrun"):
        os.mkdir("testrun")

    testdb = os.path.join("testrun/", "tests-jobs.sqlite")
    if os.path.exists(testdb):
        os.remove(testdb)

    joblogdb = DebDeployJobLog(testdb)

    yaml1 = '''
source: elinks
comment: CVE-2015-0123
fixes:
        jessie: 0.12~pre6-7
        trusty: 2.0-1
        precise:
        '''

    yamlfile = os.path.join("job1.yaml")
    if not os.path.exists(yamlfile):
        with open(yamlfile, "w") as f:
            f.write(yaml1)

    def testJobs(self):

        self.assertEqual(self.joblogdb.does_job_exist(self.yamlfile, "testsystem"), False)
        self.assertEqual(self.joblogdb.does_job_exist("fake.yaml", "testsystem"), False)
        self.assertEqual(self.joblogdb.does_job_exist(self.yamlfile, "tesstsystem"), False)

        self.joblogdb.add_job(self.yamlfile, "testsystem", "20150519122347247890")

        self.assertEqual(self.joblogdb.does_job_exist(self.yamlfile, "testsystem"), True)
        self.assertEqual(self.joblogdb.does_job_exist("fake.yaml", "testsystem"), False)
        self.assertEqual(self.joblogdb.does_job_exist(self.yamlfile, "tesstsystem"), False)

        self.assertEqual(self.joblogdb.has_been_rolled_back(self.yamlfile, "testsystem"), False)
        self.assertEqual(self.joblogdb.has_been_rolled_back("fake.yaml", "testsystem"), False)
        self.assertEqual(self.joblogdb.has_been_rolled_back(self.yamlfile, "tesstsystem"), False)

        self.assertEqual(self.joblogdb.get_jobid(self.yamlfile, "testsystem"), "20150519122347247890")
        self.assertEqual(self.joblogdb.get_jobid("fake.yaml", "testsystem"), None)
        self.assertEqual(self.joblogdb.get_jobid(self.yamlfile, "tesstsystem"), None)

        self.assertEqual(self.joblogdb.get_rollbackid(self.yamlfile, "testsystem"), "")
        self.assertEqual(self.joblogdb.get_rollbackid("fake.yaml", "testsystem"), None)
        self.assertEqual(self.joblogdb.get_rollbackid(self.yamlfile, "tesstsystem"), None)

        self.assertRaises(ValueError, self.joblogdb.mark_as_rolled_back, "10150519122347247890", "20150519122347248000")
        self.joblogdb.mark_as_rolled_back("20150519122347247890", "20150519122347248000")

        self.assertEqual(self.joblogdb.has_been_rolled_back(self.yamlfile, "testsystem"), True)
        self.assertEqual(self.joblogdb.get_rollbackid(self.yamlfile, "testsystem"), "20150519122347248000")

if __name__ == '__main__':
    unittest.main()

# Local variables:
# mode: python
# End:
